import { WorkerProfile, Job } from '../types';

export const SAMPLE_WORKERS_DATABASE: WorkerProfile[] = [
  {
    id: 'w-1',
    userId: 'u-worker-1',
    fullName: 'Ahmed Al-Hassan',
    profilePhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    phone: '070-123 45 67',
    location: 'Stockholm, Älvsjö',
    biography: 'Erfaren logistikassistent och orderplockare med 3 års vana av motviktstruck och lagersystem. Punktlig och noggrann.',
    skills: ['Logistikassistent', 'Lagerarbete', 'Truckkörning', 'Orderplock', 'Godsmottagning', 'Paketering'],
    education: 'Gymnasieexamen — Fordon & Transport',
    languages: ['Svenska', 'Engelska', 'Arabiska'],
    certificates: ['Truckkort A1-A4', 'Första Hjälpen (CPR)'],
    drivingLicenses: ['B-Körkort'],
    preferredJobCategories: ['Lager & Logistik'],
    preferredDistanceKm: 20,
    desiredHourlyRate: 165,
    rating: 4.9,
    completedAssignments: 14,
    totalHours: 216,
    bankidVerified: false,
    workHistory: [
      {
        id: 'wh-1',
        companyName: 'Svensk Logistik Solutions AB',
        jobTitle: 'Lagerarbetare & Truckförare',
        startDate: '2025-10-01',
        endDate: '2026-06-30',
        hoursWorked: 120,
        rating: 5,
        feedback: 'Enastående pålitlighet och mycket snabb i orderplocket.'
      },
      {
        id: 'wh-2',
        companyName: 'Nordic Express Distribution',
        jobTitle: 'Logistikassistent',
        startDate: '2025-02-15',
        endDate: '2025-08-30',
        hoursWorked: 96,
        rating: 4.8,
        feedback: 'Självgående och hanterar trucken säkert.'
      }
    ]
  },
  {
    id: 'w-2',
    userId: 'u-worker-2',
    fullName: 'Johan Lindqvist',
    profilePhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    phone: '073-456 78 90',
    location: 'Stockholm, Hägersten',
    biography: 'Lagerarbetare med 2 års erfarenhet av plock, pack och skanning. Innehar truckkort A1-A2 och B-körkort.',
    skills: ['Lagerarbete', 'Paketering', 'Orderplock', 'Lageradministration', 'Godshantering'],
    education: 'Gymnasieexamen',
    languages: ['Svenska', 'Engelska'],
    certificates: ['Truckkort A1-A2'],
    drivingLicenses: ['B-Körkort'],
    preferredJobCategories: ['Lager & Logistik', 'Butik & Handel'],
    preferredDistanceKm: 25,
    desiredHourlyRate: 160,
    rating: 4.8,
    completedAssignments: 11,
    totalHours: 180,
    bankidVerified: false,
    workHistory: [
      {
        id: 'wh-3',
        companyName: 'Mälardalen Lagerhub AB',
        jobTitle: 'Plockpersonal',
        startDate: '2025-05-01',
        endDate: '2025-12-15',
        hoursWorked: 90,
        rating: 4.8,
        feedback: 'Mycket bra tempo och bra samarbetsförmåga.'
      }
    ]
  },
  {
    id: 'w-3',
    userId: 'u-worker-3',
    fullName: 'Sara Berglund',
    profilePhoto: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
    phone: '072-888 99 00',
    location: 'Solna, Stockholm',
    biography: 'Noggrann distributionsmedarbetare med vana av höglager och truckkörning A1-A4. 99% närvaropålitlighet.',
    skills: ['Distributionsassistent', 'Lagerarbete', 'Truckkort A1-A4', 'Kvalitetskontroll'],
    education: 'Eftergymnasial yrkesutbildning Logistik',
    languages: ['Svenska', 'Engelska'],
    certificates: ['Truckkort A1-A4', 'Hygienpass'],
    drivingLicenses: ['B-Körkort'],
    preferredJobCategories: ['Lager & Logistik'],
    preferredDistanceKm: 15,
    desiredHourlyRate: 170,
    rating: 4.9,
    completedAssignments: 9,
    totalHours: 140,
    bankidVerified: false,
  },
  {
    id: 'w-4',
    userId: 'u-worker-4',
    fullName: 'Daniel Nilsson',
    profilePhoto: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    phone: '076-111 22 33',
    location: 'Huddinge, Stockholm',
    biography: 'Junior lagerarbetare och paketerare. Snabb, energisk och van vid tunga lyft och skiftarbete.',
    skills: ['Lagerarbete', 'Paketering', 'Sortering', 'Materialhantering'],
    education: 'Gymnasieexamen',
    languages: ['Svenska'],
    certificates: ['Truckkort A1-A4'],
    drivingLicenses: [],
    preferredJobCategories: ['Lager & Logistik', 'Bygg & Hantverk'],
    preferredDistanceKm: 20,
    desiredHourlyRate: 155,
    rating: 4.7,
    completedAssignments: 6,
    totalHours: 90,
    bankidVerified: false,
  },
  {
    id: 'w-5',
    userId: 'u-worker-5',
    fullName: 'Elena Popova',
    profilePhoto: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
    phone: '070-555 66 77',
    location: 'Stockholm, Norrmalm',
    biography: 'Utåtriktad eventvärd och butikssäljare med flytande svenska, engelska och ukrainska. Erfarenhet från mässor och butik.',
    skills: ['Event & Mässa', 'Kundtjänst', 'Kassa/Butik', 'Mässvärd', 'Språkstöd'],
    education: 'Kandidatexamen Marknadsföring',
    languages: ['Svenska', 'Engelska', 'Ukrainska'],
    certificates: ['Hygienpass'],
    drivingLicenses: ['B-Körkort'],
    preferredJobCategories: ['Event & Mässa', 'Butik & Handel', 'Administration & Kundtjänst'],
    preferredDistanceKm: 15,
    desiredHourlyRate: 160,
    rating: 4.9,
    completedAssignments: 12,
    totalHours: 175,
    bankidVerified: false,
  },
  {
    id: 'w-6',
    userId: 'u-worker-6',
    fullName: 'Marcus Ekström',
    profilePhoto: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80',
    phone: '073-222 33 44',
    location: 'Stockholm, Bromma',
    biography: 'Fysiskt stark bygghantlangare med 5 års erfarenhet av rivning, grovstäd och snickerihjälp. Säkerhetscertifierad.',
    skills: ['Bygg & Hantverk', 'Grovstäd', 'Hantlangning', 'Materialtransport', 'Rivningsarbete'],
    education: 'Bygg & Anläggningsprogrammet',
    languages: ['Svenska', 'Engelska'],
    certificates: ['Första Hjälpen (CPR)', 'Heta Arbeten', 'Ställningsbyggnad'],
    drivingLicenses: ['B-Körkort'],
    preferredJobCategories: ['Bygg & Hantverk'],
    preferredDistanceKm: 30,
    desiredHourlyRate: 175,
    rating: 4.8,
    completedAssignments: 16,
    totalHours: 320,
    bankidVerified: false,
  },
  {
    id: 'w-7',
    userId: 'u-worker-7',
    fullName: 'Fatima Zahra',
    profilePhoto: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    phone: '076-777 88 99',
    location: 'Stockholm, Kista',
    biography: 'Serviceminded butikssäljare och kassabiträde med 2 års erfarenhet från livsmedelsbutiker och modehandel.',
    skills: ['Kassa/Butik', 'Kundservice', 'Varupåfyllning', 'Inventering', 'Kassahantering'],
    education: 'Handels- & Administrationsprogrammet',
    languages: ['Svenska', 'Engelska', 'Arabiska'],
    certificates: ['Hygienpass'],
    drivingLicenses: [],
    preferredJobCategories: ['Butik & Handel', 'Hotell & Restaurang'],
    preferredDistanceKm: 15,
    desiredHourlyRate: 160,
    rating: 5.0,
    completedAssignments: 8,
    totalHours: 110,
    bankidVerified: false,
  },
  {
    id: 'w-8',
    userId: 'u-worker-8',
    fullName: 'Viktor Holm',
    profilePhoto: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
    phone: '070-999 00 11',
    location: 'Stockholm, Nacka',
    biography: 'Kock och köksbiträde med vana av högt tempo i restaurangkök, disk och servering. Innehar giltigt hygienpass.',
    skills: ['Hotell & Restaurang', 'Kökshjälp', 'Servering', 'Disk', 'Matberedning'],
    education: 'Restaurang & Livsmedel',
    languages: ['Svenska', 'Engelska'],
    certificates: ['Hygienpass'],
    drivingLicenses: ['B-Körkort'],
    preferredJobCategories: ['Hotell & Restaurang'],
    preferredDistanceKm: 20,
    desiredHourlyRate: 165,
    rating: 4.7,
    completedAssignments: 10,
    totalHours: 160,
    bankidVerified: false,
  },
  {
    id: 'w-9',
    userId: 'u-worker-9',
    fullName: 'Amina Osman',
    profilePhoto: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=400&q=80',
    phone: '072-333 44 55',
    location: 'Stockholm, Rinkeby',
    biography: 'Noggrann paketerare och orderplockare med snabba händer och positiv inställning. Punktlig och pålitlig.',
    skills: ['Paketering', 'Sortering', 'Orderplock', 'Lagerarbete', 'Etikettering'],
    education: 'Gymnasieexamen',
    languages: ['Svenska', 'Somali', 'Engelska'],
    certificates: [],
    drivingLicenses: [],
    preferredJobCategories: ['Lager & Logistik', 'Butik & Handel'],
    preferredDistanceKm: 20,
    desiredHourlyRate: 155,
    rating: 4.8,
    completedAssignments: 7,
    totalHours: 95,
    bankidVerified: false,
  },
  {
    id: 'w-10',
    userId: 'u-worker-10',
    fullName: 'Erik Svensson',
    profilePhoto: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80',
    phone: '070-444 55 66',
    location: 'Uppsala',
    biography: 'Senior lageransvarig och truckförare med 8 års erfarenhet av terminaldrift och alla truckklasser (A1-D).',
    skills: ['Lagerarbete', 'Terminalarbete', 'Truckkort A1-D', 'Arbetsledning', 'Logistikplanering'],
    education: 'Yrkeshögskola Logistikledare',
    languages: ['Svenska', 'Engelska'],
    certificates: ['Truckkort A1-D', 'Första Hjälpen (CPR)', 'ADR Farligt Gods'],
    drivingLicenses: ['B-Körkort', 'C-Körkort'],
    preferredJobCategories: ['Lager & Logistik'],
    preferredDistanceKm: 30,
    desiredHourlyRate: 195,
    rating: 4.9,
    completedAssignments: 22,
    totalHours: 460,
    bankidVerified: false,
  },
  {
    id: 'w-11',
    userId: 'u-worker-11',
    fullName: 'Linnea Söderberg',
    profilePhoto: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=400&q=80',
    phone: '073-111 44 88',
    location: 'Stockholm, Södermalm',
    biography: 'Kundtjänstmedarbetare och administratör med snabb skrivhastighet och erfarenhet av ärendehanteringssystem.',
    skills: ['Kundtjänst', 'Administration', 'Support', 'Telefoni', 'Datahantering'],
    education: 'Eftergymnasial utbildning Kundrelationer',
    languages: ['Svenska', 'Engelska'],
    certificates: [],
    drivingLicenses: ['B-Körkort'],
    preferredJobCategories: ['Administration & Kundtjänst', 'Event & Mässa'],
    preferredDistanceKm: 15,
    desiredHourlyRate: 165,
    rating: 4.9,
    completedAssignments: 13,
    totalHours: 205,
    bankidVerified: false,
  }
];
